local config = require("gitdiff.config")

describe("gitdiff configuration", function()
  after_each(function() config.setup({}) end)

  it("provides zero-configuration defaults", function()
    local value = config.setup({})
    assert.are.same("<leader>gv", value.keymap)
    assert.are.same("auto", value.picker)
    assert.are.same("select", value.merge_parent)
    assert.are.same({ "git" }, value.git_cmd)
  end)

  it("accepts a custom command and disabled mapping", function()
    local value = config.setup({ git_cmd = "gita", keymap = false })
    assert.are.same({ "gita" }, value.git_cmd)
    assert.is_false(value.keymap)
  end)

  it("rejects invalid mappings", function()
    assert.has_error(function() config.setup({ keymap = 42 }) end)
  end)

  it("accepts interactive or fixed merge-parent selection", function()
    assert.are.same("select", config.setup({ merge_parent = "select" }).merge_parent)
    assert.are.same(2, config.setup({ merge_parent = 2 }).merge_parent)
    assert.has_error(function() config.setup({ merge_parent = "first" }) end)
    assert.has_error(function() config.setup({ merge_parent = 0 }) end)
    assert.has_error(function() config.setup({ merge_parent = 1.5 }) end)
  end)
end)
